Kotlin. Homework #1. Task #3
IgorErin/Kotlin_HW pull request #3
Opened 2022-03-05 19:30 UTC by IgorErin

2022-03-07 08:56 UTC, illided requested changes
Весьма неплохо. Просто немного недочетов.

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        action.add("addToHead")
Намного лучше сделать это не строками, а каким нибудь енамом

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    fun move(indexI: Int, indexJ: Int) {
Что такое indexI и indexJ?) 

Вот я захочу воспользоваться этой функцией чтобы поменять позицию элемента. IDE мне скажет что первый аргумент indexI а второй indexJ, а как понять что это значит?)

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        require(indexJ >= 0 && indexJ < listOfNumbers.size) { "second index out of range" }
Это можно заменить на `indexI in listOfnumbers.indices`

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/indices.html

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        when (action.removeAt(action.size - 1)) {
Здесь можно (и стоит) использовать `removeLast`

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/remove-last.html

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +                listOfNumbers.removeAt(0)
Здесь `removeFirst`

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/remove-first.html

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +                listOfNumbers.removeAt(0)
Ну и во всех остальных случаях тоже

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        println(listOfNumbers.joinToString(", ", "numbers: "))
Вот в таких моментах лучше пользоваться именованными аргументами:
 `joinToString(",", prefix="numbers: ")`

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        println(listOfNumbers.joinToString(", ", "numbers: "))
Потому что мне например понадобилось в документацию заглянуть чтобы понять что это значит)

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    return stringOfCommand.split(Regex("\\s+"))
Зачем тут с регексами связываться. Сплит по пробелу не работает разве?

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    val minimumLength = 2
Вот это я уверен называется магическим числом, и если бы ты тут написал больше 2 то детект бы поругался)
Выведи лучше в приватную константу в файле

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        "TTE" -> {
Аналогичное замечание про енам

2022-03-07 08:56 UTC, illided commented on src/test/kotlin/homework1/PerformedCommandStorageTest.kt
> +
Как такое пропустил детект?)

2022-03-07 08:56 UTC, illided commented on src/test/kotlin/homework1/PerformedCommandStorageTest.kt
> +        val exception = assertFailsWith<IllegalArgumentException>(
Если лямбда аргумент находится последним, то можно опустить как именование аргумента так и круглые скобки. То есть в данном случае, раз ты все равно не указываешь сообщение можно написать:
```
assertFailsWith<IllegalArgumentException> { interaction(listOf("MOV"), storageForTestInit) }
```

2022-03-07 08:56 UTC, illided commented on src/test/kotlin/homework1/PerformedCommandStorageTest.kt
> +            block = { interaction(listOf("MOV", "7", "1"), storageForTestInit) }
А зачем добавлять сюда функцию interaction? Ты же не ее тестируешь, а исключительно класс storage.

Если хочется ее тоже, то лучше написать отдельный тест

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        println(listOfNumbers.joinToString(", ", "numbers: "))
А вообще я не понимаю зачем это надо) Классы практически никогда не работают напрямую с консолью, потому что это ненужно и даже иногда вредно. Если хочется, чтобы класс выдавал красивое форматированное сообщение, то пусть он его не печатает а отдает в виде строки, а ты потом эту строку хоть печатаешь, хоть в файл записываешь, хоть в чат телеграма отправляешь.

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    private val action = mutableListOf<String>()
Так action или actionS? :)

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    fun reversAction()
Буква e потерялась :(

2022-03-07 08:56 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    while (listOfCommand[0] != "END") {
А если будет список будет пустой?)

2022-03-07 08:56 UTC, illided commented on src/test/kotlin/homework1/PerformedCommandStorageTest.kt
> +    var storageForTestInit = PerformedCommandStorage()
Понадобилось минут 5 чтобы понять, что смысл двух стораджей в том, что один пустой а другой заполненный. Лучше это переименовать)

2022-03-07 08:56 UTC, illided commented on src/test/kotlin/homework1/PerformedCommandStorageTest.kt
> +    init {
Ух, ну ты придумал тут...
`init` конечно будет выполняться перед каждым тестом, но намного читабельнее будет если сделать функцию с аннотацией `@BeforeTest`. 

Я сильно сомневаюсь, что после изучения второго или третьего языка, вернувшись к котлину ты поймешь почему у тебя тут тесты нормально срабатывают)

2022-03-07 09:18 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        "TTE" -> {
Хотя конкретно тут конечно я не уверен что енамы сделают лучше.

2022-03-08 08:30 UTC, illided requested changes

2022-03-08 08:30 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    fun returnStringOfNumbers(): String
А это получается единственный способ получить список чисел? Если он мне нужен будет не в виде красивой строки то самому парсить придется?

2022-03-08 08:30 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    private val listOfIndexes = mutableListOf<List<Int>>()
У тебя там пары индексов, поэтому лучше держать список `Pair`. Их даже создавать просто: 
`currentIndex to finalIndex`

2022-03-08 08:30 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        val numForMove: Int = listOfNumbers[currentIndex]
Да конечно это Int, что еще то :)

2022-03-08 08:30 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +        require(actions.size >= 1) { "the stack of completed actions is empty" }
Можно заменить на `actions.isNotEmpty()`

2022-03-08 08:30 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    require(listOfCommand.isNotEmpty()) { "repeat the input, please" }
А тут используется `isNotEmpty`! Как это произошло для меня загадка :)

2022-03-08 09:37 UTC, illided approved these changes
Сейчас круто! Я бы сам такой код написал :) Пара замечаний только скажу и передам тебя Егору.

2022-03-08 09:37 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    override fun returnListOfNumbers(): List<Int> {
Я думаю здесь лучше сделать два поля: в одном ты меняешь список, а другое просто с гетером отдает неизменяемый список.
https://kotlinlang.org/docs/properties.html

2022-03-08 09:37 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +    println("Enter a number and one of the following commands separated by a space")
Лучше сделать одно большое сообщение с помощью `trimIndent()`

2022-03-08 11:05 UTC, SpirinEgor requested changes

2022-03-08 11:05 UTC, SpirinEgor commented on src/main/kotlin/homework1/task_3.kt
> +class PerformedCommandStorage : CommandStorage {
Что-то получилось совсем не то, что требовалось.
Есть класс для хранилища комманд, но он почему-то сам реализует все команды. Ожидается, что он хранит в себе лист чисел и стек некоторых `IAction`. Из методов storage -- добавить action в стек и применить его к листу, сделать обратное действие (делегация вершине стека) и получить текущий список.

2022-03-10 15:04 UTC, SpirinEgor commented
@illided тут какой-то треш, можешь посмотреть?)

2022-03-11 08:26 UTC, illided requested changes

2022-03-11 08:26 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +fun addToBegin(
Ох, не не не, у нас так не принято)
Давай переделаем это так, чтобы эти функции были полноценными классами, которые наследуются от одного интерфейса. Эти классы будут уметь применять и отменять операции, при этом не зная, что существуют другие операции. 
И пусть сторадж не будет знать что существуют разные операции, он их будет просто применять и отменять последние.

2022-03-11 08:26 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +class PerformedCommandStorage {
А еще давай все таки раскидаем разные обьекты по разным файлам)

2022-03-11 08:26 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +fun addToBegin(
Тогда из енамов сверху останется только тот, который помогает с запуском команд из консоли.

2022-03-18 13:08 UTC, SpirinEgor requested changes

2022-03-18 13:08 UTC, SpirinEgor commented on src/main/kotlin/homework1/task3/PerformedCommandStorage.kt
> +    private val listOfNumbers = mutableListOf<Int>()
Давай сделаем возможность инициализации каким-то листом

2022-03-18 13:08 UTC, SpirinEgor commented on src/main/kotlin/homework1/task3/PerformedCommandStorage.kt
> +    }
Надо определять публичный геттер для поля, а не городить свои велосипеды

2022-03-22 17:07 UTC, SpirinEgor approved these changes

2022-03-22 17:08 UTC, merged