Kotlin. Homework #3. Task #1
IgorErin/Kotlin_HW pull request #5
Opened 2022-03-30 09:25 UTC by IgorErin

2022-04-05 13:31 UTC, GirZ0n requested changes
Кажется дерево не очень сбалансированным получилось)
![image](https://user-images.githubusercontent.com/55441714/161764625-4e7794f0-6c0c-44ca-bc57-2762aa8a84e8.png)

2022-04-05 13:58 UTC, GirZ0n commented on src/main/kotlin/homework3/Tree.kt
> +        }
Даже идейка подсказывает, что здесь что-то идёт не так)

2022-04-14 15:42 UTC, GirZ0n requested changes
Почему-то падает, если я удаляю корень дерева :(
![image](https://user-images.githubusercontent.com/55441714/163422171-dde76c90-72f6-4f10-a93e-cfb159d015f5.png)

А так в целом всё норм. Оставил небольшие замечания.

2022-04-14 15:42 UTC, GirZ0n commented on src/main/kotlin/homework3/Tree.kt
> +        }
Скорее всего эту функцию лучше назвать `map`.

2022-04-14 15:42 UTC, GirZ0n commented on src/main/kotlin/homework3/Tree.kt
> +        }
А без этих строчек точно всё сломается?) Просто ты же переопределил `get` у `entries`, так что там каждый раз при обращению к этому полю должен производится обход дерева и соответственно там всегда будут актуальные вхождения.

2022-04-14 15:42 UTC, GirZ0n commented on src/main/kotlin/homework3/Tree.kt
> +            return "{${node.value} : [${visitToString(node.left)}, ${visitToString(node.right)}]}"
Кажется, что будет удобнее, если ты перенесёшь этот код в `Node`.

2022-04-14 15:42 UTC, GirZ0n commented on src/main/kotlin/homework3/Tree.kt
> +            return "{${node.value} : [${visitToString(node.left)}, ${visitToString(node.right)}]}"
И ещё ты тут выводишь только `value`, хотелось бы ещё и `key` видеть)

2022-04-14 15:42 UTC, GirZ0n commented on src/main/kotlin/homework3/Tree.kt
> +            return "{${node.value} : [${visitToString(node.left)}, ${visitToString(node.right)}]}"
Ну и после того, как перенесёшь, кажется что смысла в этой функции не будет, можно будет сразу всё нужное написать в `toString`.

2022-04-16 12:43 UTC, GirZ0n approved these changes
Оставил ещё небольшие замечания, а так всё норм) Зову Егора)

2022-04-16 12:43 UTC, GirZ0n commented on src/main/kotlin/homework3/Tree.kt
> +            return searchNode
```kotlin
return when {
    key < node.key -> searchWithKey(node.left, key)
    key > node.key -> searchWithKey(node.right, key)
    key == node.key -> node
}
```

2022-04-16 12:43 UTC, GirZ0n commented on src/main/kotlin/homework3/Node.kt
> +                if (rightNodeBalance < 0) this.rightLeftRotate() else this.leftRotate()
```kotlin
if (rightNodeBalance < 0) {
    this.rightLeftRotate() 
} else  {
    this.leftRotate()
}
```

2022-04-16 12:43 UTC, GirZ0n commented on src/main/kotlin/homework3/Node.kt
> +                if (leftNodeBalance > 0) this.leftRightRotate() else this.rightRotate()
Тут тоже поправь

2022-04-16 12:43 UTC, GirZ0n commented on src/main/kotlin/homework3/Tree.kt
> +    override fun isEmpty(): Boolean = root == null
Кажется, что лучше проверять все же здесь `size`: `size == 0`.

2022-04-18 12:27 UTC, SpirinEgor approved these changes
👍

2022-04-18 12:27 UTC, merged