Kotlin. Homework #4. Task #1
IgorErin/Kotlin_HW pull request #6
Opened 2022-05-06 09:41 UTC by IgorErin

2022-05-29 22:39 UTC, elena-lyulina requested changes
Все выглядит очень красиво, ты молодец и сделал классную работу! отдельное спасибо за архитектуру, выглядит очень прилично
единственный коммент -- хочется получше тесты, попробуй генерировать списки с большим количеством элементов и тестировать их с большими количествами потоков/корутинов -- сейчас у тебя несколько вручную выбранных списков и количеств потоков, выглядит чуть грустно по сравнению с остальным кодом

2022-05-30 23:25 UTC, IgorErin commented
Здравствуйте! Я изменил тесты... Относительно количества потоков/корутин: я увеличил их до 2^12, 2^15 соответсветнно, надеюсь этого достаточно...

2022-06-01 12:19 UTC, elena-lyulina approved these changes
совсем чуть-чуть осталось

2022-06-01 12:19 UTC, elena-lyulina commented on src/test/kotlin/homework4/coroutins/MergeSortWithCoroutinesTest.kt
> +            Arguments.of(smallList(), -1),
если еще этот длинный список сможешь автоматически генерировать как перебор всех вариантов списка и номера потоков/корутинов, то совсем будет круто

2022-06-01 12:19 UTC, elena-lyulina commented on src/test/kotlin/homework4/threads/MergeSortWithThreadsTest.kt
> +            Arguments.of(smallList(), -1),
ну и тут (это можно куда-то вынести, чтобы не повторять, например)

2022-06-02 12:09 UTC, elena-lyulina approved these changes
Класс!

2022-06-02 12:09 UTC, merged